name: Beszel-agent build
on:
  workflow_dispatch:
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/beszel-agent
      DATE_TAG: $(date +'%Y%m%d')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull beszel-agent code
        run: |
          git clone https://github.com/henrygd/beszel.git beszel

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

              # 构建Docker镜像（支持多平台）并推送到DockerHub，同时打上日期标签
      - name: Build and push Docker image with tags
        run: |
          cd beszel/beszel
          docker buildx build --platform linux/s390x,linux/amd64 \
            --file dockerfile_Agent \
            -t $IMAGE_NAME . --push