name: Beszel build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - run

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/beszel-agent
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull beszel code
        run: |
          git clone https://github.com/henrygd/beszel.git beszel

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并推送到DockerHub，同时打上日期标签
      - name: Build and push beszel-agent
        run: |
          cd beszel/beszel
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le,linux/riscv64 \
            --file dockerfile_Agent \
            -t $IMAGE_NAME:$(date +'%Y%m%d') \
            -t $IMAGE_NAME \
            . --push


      # 打包WEB
      - name: Build web
        run: |
          cd beszel/beszel/site/src
          npm i
          npm run build

      # 构建Docker镜像（支持多平台）并推送到DockerHub，同时打上日期标签
      - name: Build and push beszel
        run: |
          cd beszel/beszel
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le,linux/riscv64 \
            --file dockerfile_Hub \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/beszel:$(date +'%Y%m%d') \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/beszel \
            . --push
      
      

      

