name: docker-hub-copy
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'A JSON array of images to sync, e.g., ["user/repo1", "user/repo2"]'
        required: false
        default: '["ygkkk/argosbx"]'
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - run

env:
  DESTINATION_USER: smanx

jobs:
  copy-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(github.event.inputs.images || '["ygkkk/argosbx"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 拉取、标记并推送多架构 Docker 镜像
        run: |
          SOURCE_IMAGE=${{ matrix.image }}
          IMAGE_NAME=$(echo $SOURCE_IMAGE | cut -d'/' -f2)
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          DESTINATION_IMAGE=${{ env.DESTINATION_USER }}/${IMAGE_NAME}:${TIMESTAMP}
          
          # 复制并添加时间戳标签
          docker buildx imagetools create --tag $DESTINATION_IMAGE $SOURCE_IMAGE
          
          # 同时推送latest标签
          docker buildx imagetools create --tag ${{ env.DESTINATION_USER }}/${IMAGE_NAME}:latest $SOURCE_IMAGE
