name: docker-hub-copy
on:
  workflow_dispatch:
    inputs:
      images:
        description: '要同步的镜像的 JSON 数组，例如：["user/repo1", "user/repo2"]'
        required: false
        default: '["ygkkk/argosb"]'
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - push-all

env:
  DESTINATION_USER: smanx

jobs:
  copy-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(github.event.inputs.images || '["ygkkk/argosb"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 拉取、标记并推送多架构 Docker 镜像
        run: |
          SOURCE_IMAGE=${{ matrix.image }}
          IMAGE_NAME=$(echo $SOURCE_IMAGE | cut -d'/' -f2)
          DESTINATION_IMAGE=${{ env.DESTINATION_USER }}/${IMAGE_NAME}

          # 拉取源镜像的 manifest list
          docker buildx imagetools create --dry-run $SOURCE_IMAGE > manifest.json

          # 在 manifest 中将源镜像名称替换为目标镜像名称
          # 这假设 manifest.json 中的源镜像名称可以直接替换。
          # 对于更复杂的场景，可能需要适当的 JSON 解析工具。
          sed -i "s|${SOURCE_IMAGE}|${DESTINATION_IMAGE}|g" manifest.json

          # 将修改后的 manifest list 推送到目标
          docker buildx imagetools create --file manifest.json $DESTINATION_IMAGE
