name: Docker Multi Pull

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  pull-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Load cached images
        run: |
          mkdir -p /tmp/docker-cache
          if [ -d "/tmp/docker-cache" ]; then
            for image in /tmp/docker-cache/*.tar; do
              [ -f "$image" ] && docker load -i "$image" || true
            done
          fi
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull Docker Images
        run: |
          # 将变量内容保存到文件中并确保使用 Unix 格式的换行符
          echo "${{ vars.DOCKER_IMAGES }}" | tr -d '\r' > images.txt
          
          # 读取文件并处理每一行
          while IFS=' ' read -r image_name pull_count || [ -n "$image_name" ]; do
            if [ -z "$image_name" ]; then
              continue
            fi
            
            # 清理 pull_count 中的任何非数字字符
            pull_count=$(echo "$pull_count" | tr -cd '0-9')
            
            echo "Processing image: $image_name, pull count: $pull_count"
            
            # 循环拉取指定次数
            for ((i=1; i<=$pull_count; i++)); do
              echo "Pull attempt $i for $image_name"
              docker pull "$image_name" > /dev/null 2>&1
              
              # 只在最后一次循环时保存镜像到缓存
              if [ $i -eq $pull_count ]; then
                image_filename=$(echo "$image_name" | tr '/:' '_')
                docker save "$image_name" -o "/tmp/docker-cache/${image_filename}.tar"
                echo "Image saved to /tmp/docker-cache/${image_filename}.tar"
              fi
              
              sleep 1
            done
          done < images.txt 