name: docker-hub-copy
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'A JSON array of images to sync, e.g., ["user/repo1", "user/repo2"]'
        required: false
        default: '["ygkkk/argosb"]'
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - push-all

env:
  DESTINATION_USER: smanx

jobs:
  copy-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(github.event.inputs.images || '["ygkkk/argosb"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull, Tag and Push Docker Image
        run: |
          IMAGE_NAME=$(echo ${{ matrix.image }} | cut -d'/' -f2)
          docker pull ${{ matrix.image }}
          docker tag ${{ matrix.image }} ${{ env.DESTINATION_USER }}/${IMAGE_NAME}
          docker push ${{ env.DESTINATION_USER }}/${IMAGE_NAME}
