name: Dpanel build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Dpanel code
        run: |
          git clone https://github.com/donknap/dpanel.git dpanel

      - name: Build Dpanel
        run: |
          cd dpanel
          go build
