name: Dpanel build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Dpanel code
        run: |
          git clone https://github.com/donknap/dpanel.git dpanel

      - name: Build Dpanel
        run: |
          cd dpanel
          GOOS=linux GOARCH=amd64 go build -o dpanel-amd64
          GOOS=linux GOARCH=arm64 go build -o dpanel-arm64
          GOOS=linux GOARCH=386 go build -o dpanel-386
          GOOS=linux GOARCH=ppc64le go build -o dpanel-ppc64le
          GOOS=linux GOARCH=s390x go build -o dpanel-s390x
          ls
