name: eazy-cp build
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'latest'
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: eazy-cp  # 项目名称
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/eazy-cp  # 镜像名称
      REPO_URL: ${{ vars.REPO_URL }}        # 新增：仓库URL变量
      REPO_PATH: ${{ vars.REPO_PATH }}      # 新增：仓库本地路径变量
      build_tag: ""  # 新增：定义 build_tag 变量

    steps:
      # 拉取私有仓库代码（使用 GitHub PAT）
      - name: Pull project code
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git clone https://$REPO_ACCESS_TOKEN@$REPO_URL $REPO_PATH

      # 新增步骤：拷贝 Dockerfile
      - name: Copy Dockerfile to out directory
        run: |
          cp -r $REPO_PATH/$PROJECT_NAME/ $PROJECT_NAME/

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录 DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建
      - name: Build App and push Docker image with tags
        run: |
          cd $PROJECT_NAME
          BUILD_TAGS="-t $IMAGE_NAME:latest"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            $BUILD_TAGS \
            . --push
            