name: moon tv build
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'latest'
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - run

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/moontv
      REPO_URL: ${{ vars.REPO_URL }}        # 新增：仓库URL变量
      REPO_PATH: ${{ vars.REPO_PATH }}      # 新增：仓库本地路径变量
      BUILD_TAG: ""  # 新增：定义 BUILD_TAG 变量
      CODE_GITHUB: "Stardm0/MoonTV"
      CODE_PATH: "MoonTV"

    steps:
      - name: Get tag based on build_type
        run: |
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          if [[ "$BUILD_TYPE" == "latest" || "$BUILD_TYPE" == "" ]]; then
            # 获取最新tag
            LATEST_TAG=$(curl -s https://api.github.com/repos/${{env.CODE_GITHUB}}/tags | jq -r '.[0].name')
            echo "BUILD_TAG=$LATEST_TAG" >> $GITHUB_ENV
            echo "使用最新标签: $LATEST_TAG"
          else
            echo "BUILD_TAG=$BUILD_TYPE" >> $GITHUB_ENV
            echo "使用指定标签: $BUILD_TYPE"
          fi

      # 使用 actions/checkout 替代 git clone，更符合 GitHub Actions 最佳实践
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CODE_GITHUB }}
          ref: ${{ env.BUILD_TAG }}
          path: ${{ env.CODE_PATH }}

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录 DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 新增步骤：检查 Docker Hub 上的镜像标签是否存在
      - name: Check if Docker Hub image tag exists
        id: check_tag
        run: |
          if docker manifest inspect $IMAGE_NAME:${{ env.BUILD_TAG }} &> /dev/null; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
      
      # 构建
      - name: Build App and push Docker image with tags
        run: |
          cd ${{env.CODE_PATH}}
          # 始终包含 latest 标签
          BUILD_TAGS="-t $IMAGE_NAME:latest"
          # 如果指定标签不存在，则添加指定标签
          if [[ "${{ steps.check_tag.outputs.tag_exists }}" == "false" ]]; then
            BUILD_TAGS="$BUILD_TAGS -t $IMAGE_NAME:${{ env.BUILD_TAG }}"
          fi
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            $BUILD_TAGS \
            . --push
