name: QQ base build
on:
  workflow_dispatch:
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-qq
      REPO_URL: ${{ vars.REPO_URL }}        # 新增：仓库URL变量
      REPO_PATH: ${{ vars.REPO_PATH }}   
    steps:
      # 拉取私有仓库代码（使用 GitHub PAT）
      - name: Pull project code
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git clone https://$REPO_ACCESS_TOKEN@$REPO_URL $REPO_PATH

      # 设置 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录 DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建 Docker 镜像（支持多平台）并推送到 DockerHub
      - name: Build and push Docker image with tags
        run: |
          cd $REPO_PATH/qq
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile-base \
            -t $IMAGE_NAME:base-$(date +'%Y%m%d') \
            -t $IMAGE_NAME:base \
            . --push