name: sryzen build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/sryzen
      REPO_PATH: ${{ vars.REPO_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull code
        run: |
          git clone https://github.com/smanx/sryzen.git $REPO_PATH

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并推送到DockerHub，同时打上日期标签
      - name: Build and push
        run: |
          cd $REPO_PATH
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6 \
            -t $IMAGE_NAME:$(date +'%Y%m%d') \
            -t $IMAGE_NAME \
            . --push
      
      

      

