name: v2rayN final build
on:
  workflow_dispatch:
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-v2rayn
    steps:
      # 拉取私有仓库代码（使用 GitHub PAT）
      - name: Pull docker-project code
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git clone https://$REPO_ACCESS_TOKEN@github.com/smanx/docker-project.git docker-project

          - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push multi-platform, multi-tag image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # 多平台
          push: true
          tags: |
            $IMAGE_NAME:test1
            $IMAGE_NAME:test2