name: webui-aria build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00触发
  push:
    branches:
      - push-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        PROJECT_NAME: webui-aria  # 项目名称
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/webui-aria  # 镜像名称
        REPO_URL: ${{ vars.REPO_URL }}        # 新增：仓库URL变量
        REPO_PATH: ${{ vars.REPO_PATH }}      # 新增：仓库本地路径变量
    steps:

      - name: Pull code
        run: |
          git clone https://github.com/smanx/webui-aria2.git $PROJECT_NAME

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并推送到DockerHub
      - name: Build and push beszel-agent
        run: |
          cd $PROJECT_NAME
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le,linux/riscv64 \
            --file dockerfile_Agent \
            -t $IMAGE_NAME:$(date +'%Y%m%d') \
            -t $IMAGE_NAME \
            . --push
      

      

